-- 코드를 입력하세요
SELECT FLAVOR from
(SELECT j.FLAVOR, j.TOTAL_ORDER from JULY as j LEFT JOIN FIRST_HALF as f ON j.FLAVOR = f.FLAVOR 
UNION
SELECT f.FLAVOR, f.TOTAL_ORDER from JULY as j RIGHT JOIN FIRST_HALF as f ON j.FLAVOR = f.FLAVOR) as sub
GROUP BY FLAVOR
ORDER by SUM(TOTAL_ORDER) DESC
LIMIT 3;

