-- 코드를 입력하세요
SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE,
    (SELECT PRODUCT_NAME 
     FROM FOOD_PRODUCT AS sub
     WHERE sub.CATEGORY = fp.CATEGORY
     ORDER BY sub.PRICE DESC
     LIMIT 1) AS PRODUCT_NAME
FROM FOOD_PRODUCT AS fp
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY
ORDER BY MAX_PRICE DESC;