-- 코드를 입력하세요
SELECT CAR_ID, ROUND(AVG((END_DATE - START_DATE)+1),1) as AVERAGE_DURATION  
from CAR_RENTAL_COMPANY_RENTAL_HISTORY
group by CAR_ID
having ROUND(AVG((END_DATE - START_DATE)+1),1) >= 7
order by ROUND(AVG((END_DATE - START_DATE)+1),1) DESC, CAR_ID DESC;