-- 코드를 입력하세요
SELECT 
    CAR_ID, 
    TO_CHAR(ROUND(AVG(END_DATE - START_DATE + 1), 1), 'FM9990.0') as AVERAGE_DURATION  
from CAR_RENTAL_COMPANY_RENTAL_HISTORY
group by CAR_ID
having ROUND(AVG(END_DATE - START_DATE)+1,2) >= 7
order by AVERAGE_DURATION DESC, CAR_ID DESC;