-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') as REVIEW_DATE
FROM MEMBER_PROFILE m 
JOIN REST_REVIEW r ON r.MEMBER_ID = m.MEMBER_ID
WHERE r.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW 
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        SELECT MAX(REVIEW_COUNT)
        FROM (
            SELECT MEMBER_ID, COUNT(*) AS REVIEW_COUNT
            FROM REST_REVIEW 
            GROUP BY MEMBER_ID
        ) review_counts
    )
)
ORDER BY REVIEW_DATE, REVIEW_TEXT;