-- 코드를 입력하세요
SELECT FLAVOR
FROM (
    SELECT 
        fh.FLAVOR,
        (fh.TOTAL_ORDER + COALESCE(SUM(j.TOTAL_ORDER), 0)) AS TOTAL_SUM,
        ROW_NUMBER() OVER (ORDER BY (fh.TOTAL_ORDER + COALESCE(SUM(j.TOTAL_ORDER), 0)) DESC) AS rn
    FROM FIRST_HALF fh
    LEFT JOIN JULY j ON fh.FLAVOR = j.FLAVOR
    GROUP BY fh.FLAVOR, fh.TOTAL_ORDER
) ranked_flavors
WHERE rn <= 3