-- 코드를 입력하세요
SELECT FLAVOR
FROM (
    SELECT 
        fh.FLAVOR, 
        (fh.TOTAL_ORDER + COALESCE(SUM(j.TOTAL_ORDER), 0)) AS TOTAL_SUM
    FROM FIRST_HALF fh
    LEFT JOIN JULY j 
    ON fh.FLAVOR = j.FLAVOR
    GROUP BY fh.FLAVOR, fh.TOTAL_ORDER
    ORDER BY TOTAL_SUM DESC
) 
WHERE ROWNUM <= 3;

