-- 코드를 입력하세요
SELECT 
    MONTH(START_DATE) as MONTH, 
    CAR_ID, 
    COUNT(HISTORY_ID) as RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY as r
WHERE r.CAR_ID IN (
    SELECT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31' 
    GROUP BY CAR_ID
    HAVING COUNT(HISTORY_ID) != 0 AND COUNT(HISTORY_ID) >= 5
)
AND r.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH(START_DATE), CAR_ID 
ORDER BY MONTH, CAR_ID DESC;