-- 코드를 입력하세요
SELECT DISTINCT h.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR c 
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
ON c.CAR_ID = h.CAR_ID
WHERE CAR_TYPE = '세단' 
AND TO_CHAR(h.start_date, 'YYYY-MM') = '2022-10'
ORDER BY h.CAR_ID DESC;