-- 코드를 입력하세요
SELECT 
    fp.CATEGORY, 
    fp.PRICE AS MAX_PRICE,
    fp.PRODUCT_NAME
       
FROM FOOD_PRODUCT fp
WHERE fp.PRICE = (
    SELECT MAX(PRICE)
    FROM FOOD_PRODUCT 
    WHERE CATEGORY = fp.CATEGORY
)
AND fp.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC;